apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqltool
  namespace: lcnc-multiagent-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqltool
  template:
    metadata:
      labels:
        app: sqltool
    spec:
      containers:
        - name: sqltool
          image: your-docker-repo/sqltool:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sqltool-db-secret
                  key: database-url
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: regcred